disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - force_unwrapping
  - trailing whitespace
  
opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - VODA_iOS/SupportingFiles/AppDelegate.swift
  - VODA_iOS/SupportingFiles/SceneDelegate.swift

force_cast: warning # implicitlyß
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 110
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"]
  
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
