
   
# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'VODA_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'Moya'
    pod 'Kingfisher'
    pod 'SwiftLint'
    pod 'lottie-ios'
    pod 'SoundWave'

    pod 'GoogleSignIn'
    pod 'KakaoSDK'
    
    pod 'DropDown'
    
  # Pods for VODA_iOS

end