# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'VODA_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VODA_iOS
    pod 'Moya'
    pod 'Kingfisher', '7.2.0'
    pod 'SwiftLint', '0.46.5'
    pod 'lottie-ios', '3.5.0'
    pod 'SoundWave'

    pod 'GoogleSignIn'
    pod 'KakaoSDK', '2.5.6'
    pod 'Firebase/Messaging'

    pod 'DropDown'
    
  target 'APIServiceTests' do
    inherit! :search_paths
    # Pods for testing
  end


end